<?php

namespace Aip\ProfilageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtapeConfigueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeConfigueRepository extends EntityRepository
{
}
